#!/bin/bash

echo "=========================================="
echo "Railway Environment Variables Setup"
echo "=========================================="
echo ""
echo "I need 2 pieces of information from you:"
echo ""
echo "1. DATABASE_URL - Your Neon Postgres connection string"
echo "   Format: postgresql://username:password@host/database"
echo ""
echo "2. ADMIN_PASSWORD - A secure password for admin login"
echo ""
echo "Once you provide these, I'll add all variables to Railway."
echo ""
echo "=========================================="
echo ""
echo "The other variables are already set:"
echo "- JWT_SECRET: xTs4ts/WPRsugSRr4W/rcM47EAtnyOQDo5nL932Ecig="
echo "- JWT_EXPIRES_IN: 7d"
echo "- ADMIN_EMAIL: dylan.barrett@embeddedcounsel.com"
echo "- PORT: 3001"
echo ""
